# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/generic.ipynb.

# %% auto 0
__all__ = ['load_pickle', 'dump_pickle']

# %% ../nbs/generic.ipynb 3
import os
import pickle

# %% ../nbs/generic.ipynb 4
def load_pickle(pickle_file):
    "read a pickle file"
    if os.path.isfile(pickle_file) == False:
        return
    with open(pickle_file, "rb") as h:
        result = pickle.load(h)
    return result

# %% ../nbs/generic.ipynb 5
def dump_pickle(obj,pickle_file,protocol=3):
    "dump an object to pickle file"
    with open("pickle_file", "wb") as h:
        pickle.dump(obj, h, protocol=protocol)
    return 
